const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Behaviors.solid,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.JavaScriptInEvents.FFase1_Event10_Act2,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.JavaScriptInEvents.FFase1_Event15_Act2,
		C3.Plugins.System.Cnds.Else,
		C3.JavaScriptInEvents.FFase1_Event24_Act2,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTapGestureObject
	];
};
self.C3_JsPropNameTable = [
	{Teclado: 0},
	{Vida: 0},
	{tomardano: 0},
	{Comida: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{Piscar: 0},
	{CapitãoPrensadão: 0},
	{Âncora: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sólido: 0},
	{BlocoEsquerda: 0},
	{BlocoDireita: 0},
	{BlocoDoMeio: 0},
	{BlocodoMeio2: 0},
	{Bacia: 0},
	{DestruirExternamente: 0},
	{Projétil: 0},
	{Tiro: 0},
	{rampa1: 0},
	{canto2: 0},
	{terra2: 0},
	{canto1: 0},
	{rampa2: 0},
	{carriola: 0},
	{caixa: 0},
	{Monstro: 0},
	{Monstro3: 0},
	{grama1: 0},
	{core: 0},
	{vida: 0},
	{BotãoDeTiro: 0},
	{pular: 0},
	{moverEsquerda: 0},
	{moverDireita: 0},
	{Toque: 0},
	{marcador: 0},
	{gramaesquerdaa: 0},
	{gramadireita: 0},
	{cerdaEsquerda: 0},
	{cercameio: 0},
	{cercaDireita: 0},
	{bau: 0},
	{pedra: 0},
	{lustre: 0},
	{Sprite5: 0},
	{Sprite: 0},
	{GameOver: 0},
	{JogarNovamente: 0},
	{Sair: 0},
	{Partículas: 0},
	{cachorroQuente: 0},
	{Partículas2: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Áudio: 0},
	{lava: 0},
	{cachorron: 0},
	{cachorro: 0},
	{Cliente: 0},
	{inciio: 0},
	{Senóide: 0},
	{vertical: 0},
	{horizontal: 0},
	{Monstro2: 0},
	{portal: 0},
	{controles: 0},
	{cachorroInicial: 0},
	{ovoinicio: 0},
	{inimigosinicio: 0},
	{logoinicio: 0},
	{cachorroincio: 0},
	{batatainicio: 0},
	{Mouse: 0},
	{Monstro4: 0},
	{Texto: 0},
	{Jogar: 0},
	{portal2: 0},
	{Vidas: 0}
];

self.InstanceType = {
	Teclado: class extends self.IInstance {},
	CapitãoPrensadão: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	BlocoEsquerda: class extends self.ISpriteInstance {},
	BlocoDireita: class extends self.ISpriteInstance {},
	BlocoDoMeio: class extends self.ISpriteInstance {},
	BlocodoMeio2: class extends self.ISpriteInstance {},
	Bacia: class extends self.ISpriteInstance {},
	Tiro: class extends self.ISpriteInstance {},
	rampa1: class extends self.ISpriteInstance {},
	canto2: class extends self.ISpriteInstance {},
	terra2: class extends self.ISpriteInstance {},
	canto1: class extends self.ISpriteInstance {},
	rampa2: class extends self.ISpriteInstance {},
	carriola: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	Monstro3: class extends self.ISpriteInstance {},
	grama1: class extends self.ISpriteInstance {},
	core: class extends self.ISpriteInstance {},
	vida: class extends self.ITextInstance {},
	BotãoDeTiro: class extends self.ISpriteInstance {},
	pular: class extends self.ISpriteInstance {},
	moverEsquerda: class extends self.ISpriteInstance {},
	moverDireita: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	marcador: class extends self.ISpriteInstance {},
	gramaesquerdaa: class extends self.ISpriteInstance {},
	gramadireita: class extends self.ISpriteInstance {},
	cerdaEsquerda: class extends self.ISpriteInstance {},
	cercameio: class extends self.ISpriteInstance {},
	cercaDireita: class extends self.ISpriteInstance {},
	bau: class extends self.ISpriteInstance {},
	pedra: class extends self.ISpriteInstance {},
	lustre: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	GameOver: class extends self.ITextInstance {},
	JogarNovamente: class extends self.ITextInstance {},
	Sair: class extends self.ITextInstance {},
	Partículas: class extends self.IParticlesInstance {},
	cachorroQuente: class extends self.ISpriteInstance {},
	Partículas2: class extends self.IParticlesInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Áudio: class extends self.IInstance {},
	lava: class extends self.ISpriteInstance {},
	cachorron: class extends self.ITextInstance {},
	cachorro: class extends self.ISpriteInstance {},
	Cliente: class extends self.ISpriteInstance {},
	inciio: class extends self.ITiledBackgroundInstance {},
	vertical: class extends self.ISpriteInstance {},
	horizontal: class extends self.ISpriteInstance {},
	Monstro2: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	controles: class extends self.ISpriteInstance {},
	cachorroInicial: class extends self.ISpriteInstance {},
	ovoinicio: class extends self.ISpriteInstance {},
	inimigosinicio: class extends self.ISpriteInstance {},
	logoinicio: class extends self.ISpriteInstance {},
	cachorroincio: class extends self.ISpriteInstance {},
	batatainicio: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Monstro4: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Jogar: class extends self.ITextInstance {},
	portal2: class extends self.ISpriteInstance {}
}